networks:
  traefik-internetwork:
    external: true

volumes:
  wireguard-data:
    driver: local

services:
  core:
    image: ghcr.io/wg-easy/wg-easy:15.1
    volumes:
      - wireguard-data:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    environment:
    # To make it work:
    # 1. Set modprobe iptable_nat and modprobe iptable
    # 2. Set sysctl net.ipv4.ip_forward=1
    #               net.ipv4.conf.all.src_valid_mark=1
    #               net.ipv6.conf.all.disable_ipv6=0
    #               net.ipv6.conf.all.forwarding=1
    #               net.ipv6.conf.default.forwarding=1
    # 3. Set:
    #  WG_POST_UP=iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -j MASQUERADE; iptables -A FORWARD -o %i -j ACCEPT
    #  WG_POST_DOWN=iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -j MASQUERADE; iptables -D FORWARD -o %i -j ACCEPT
      - INSECURE=true
      - DISABLE_IPV6=true
      - INIT_HOST=${WG_HOST}
      - INIT_IPV4_CIDR=10.123.0.0/14
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    networks:
      - traefik-internetwork
    ports:
        - target: 51821
          published: 8081
          protocol: tcp
          mode: ingress
        - target: 51820
          published: 51822
          protocol: udp
          mode: host
    deploy:
      placement:
        constraints:
          - node.labels.database == master
      mode: replicated
      replicas: 1
      # labels:
      #   - "traefik.enable=true"
      #   - "traefik.swarm.network=traefik-internetwork"
      #   - "traefik.http.routers.wireguard-http.entrypoints=web"
      #   - "traefik.http.routers.wireguard-http.rule=Host(`wg.mcb-svc.work`)"
      #   - "traefik.http.routers.wireguard-http.middlewares=wireguard-https"
      #   - "traefik.http.routers.wireguard-http.service=wireguard"
      #   - "traefik.http.services.wireguard.loadbalancer.server.port=51821"
      #   - "traefik.http.middlewares.wireguard-https.redirectscheme.scheme=https"
      #   - "traefik.http.routers.wireguard.entrypoints=websecure"
      #   - "traefik.http.routers.wireguard.rule=Host(`wg.mcb-svc.work`)"
      #   - "traefik.http.routers.wireguard.tls=true"
      #   - "traefik.http.routers.wireguard.tls.certresolver=letsencrypt"
