apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key-eso
  namespace: administrator-apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-secret-key-eso
    creationPolicy: Owner
  data:
    - secretKey: authentik-secret-key
      remoteRef:
        key: docker-secrets
        property: authentik-secret-key

