apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-cert-eso
  namespace: administrator-apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-cert-eso
    creationPolicy: Owner
    template:
      data:
        cloudflare-cert-pem-b64: '{{ index . "cloudflare-cert-pem-b64" | b64dec }}'
  data:
    - secretKey: cloudflare-cert-pem-b64
      remoteRef:
        key: terraform
        property: cloudflare-cert-pem-b64

