apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-db-password-eso
  namespace: administrator-apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-db-password-eso
    creationPolicy: Owner
  data:
    - secretKey: authentik-db-password
      remoteRef:
        key: docker-secrets
        property: authentik-db-password
