apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-key-eso
  namespace: administrator-apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-key-eso
    creationPolicy: Owner
    template:
      data:
        cloudflare-key-pem-b64: '{{ index . "cloudflare-key-pem-b64" | b64dec }}'
  data:
    - secretKey: cloudflare-key-pem-b64
      remoteRef:
        key: terraform
        property: cloudflare-key-pem-b64

