apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-client-id-eso
  namespace: administrator-apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: s3-client-id-eso
    creationPolicy: Owner
  data:
    - secretKey: s3-client-id
      remoteRef:
        key: docker-secrets
        property: s3-client-id

