apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd-system
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://traefik.github.io/charts
    targetRevision: 36.3.0
    chart: traefik
    helm:
      valueFiles:
        - $values/k8s/helm-values/traefik-values-oracle-k3s.yaml
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 36.3.0
      helm:
        valueFiles:
          - $values/k8s/helm-values/rancher-values.yaml
    - repoURL: git@github.com:HuyNguyen2109/My-DevOps.git
      targetRevision: develop
      ref: values
  project: homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
