service:
  ui:
    type: Rancher-Proxy
  manager:
    type: ClusterIP
longhornUI:
  replicas: 2
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - longhorn-ui
            topologyKey: kubernetes.io/hostname
  nodeSelector:
    node.kubernetes.io/worker: "true"
    topology.kubernetes.io/region: "sg-prod-01"
defaultSettings:
  defaultDataPath: "/var/lib/longhorn"
enablePSP: false

persistence:
  defaultClassReplicaCount: 2

defaultBackupStore:
  backupTarget: "s3://longhorn@auto/"
  backupTargetCredentialSecret: "minio-secret-eso"
