global:
  nodeSelector:
    node.kubernetes.io/worker: "true"
    topology.kubernetes.io/region: "sg-prod-01"

networkPolicies:
  enabled: true
  type: "k3s"

service:
  ui:
    type: Rancher-Proxy
  manager:
    type: ClusterIP
longhornUI:
  replicas: 2
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - longhorn-ui
            topologyKey: kubernetes.io/hostname
defaultSettings:
  defaultDataPath: "/var/lib/longhorn"
  v2DataEngineGuaranteedInstanceManagerCPU: "800"
enablePSP: false

persistence:
  defaultClassReplicaCount: 2
  reclaimPolicy: "Retain"
  migratable: true
  dataEngine: v2

defaultBackupStore:
  backupTarget: "s3://longhorn@auto/"
  backupTargetCredentialSecret: "minio-secret-eso"

longhornManager:
  log:
    format: json

longhornDriver:
  log:
    format: json
