apiVersion: v1
kind: Namespace
metadata:
  name: argocd-system
  labels:
    kubernetes.io/metadata.name: argocd-system
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: privileged
