apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-password-eso
  namespace: administrator-apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-admin-password-eso
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: docker-secrets
        property: harbor-admin-password

