# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
services:
  manager:
    image: wazuh/wazuh-manager:${IMAGE_TAG}
    networks:
      traefik-internetwork:
        aliases:
          - wazuh.manager
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.codename == ${WAZUH_MANAGER_NODE_CODENAME}
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=${INDEXER_ADMIN_USERNAME}
      - INDEXER_PASSWORD=${INDEXER_ADMIN_PASSWORD}
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
    configs:
      - source: wazuh-manager-config
        target: /wazuh-config-mount/etc/ossec.conf
      - source: wazuh.manager.pem
        target: /etc/ssl/filebeat.pem
      - source: wazuh.manager-key.pem
        target: /etc/ssl/filebeat.key
      - source: root-ca-manager.pem
        target: /etc/ssl/root-ca.pem
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat

  indexer:
    image: wazuh/wazuh-indexer:${IMAGE_TAG}
    networks:
      traefik-internetwork:
        aliases:
          - wazuh.indexer
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure  
      placement:
        constraints:
          - node.labels.codename == ${WAZUH_INDEXER_NODE_CODENAME}
      resources:
        limits:
          cpus: '3.0'
          memory: 8G
        reservations:
          cpus: '1.0'
          memory: 2G
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    configs:
      - source: wazuh-indexer-config
        target: /usr/share/wazuh-indexer/config/opensearch.yml
      - source: internal-users-config
        target: /usr/share/wazuh-indexer/config/opensearch-security/internal_users.yml
      - source: root-ca.pem
        target: /usr/share/wazuh-indexer/config/certs/root-ca.pem
      - source: wazuh.indexer.pem
        target: /usr/share/wazuh-indexer/config/certs/wazuh.indexer.pem
      - source: wazuh.indexer-key.pem
        target: /usr/share/wazuh-indexer/config/certs/wazuh.indexer.key
      - source: admin.pem
        target: /usr/share/wazuh-indexer/config/certs/admin.pem
      - source: admin-key.pem
        target: /usr/share/wazuh-indexer/config/certs/admin-key.pem
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer

  dashboard:
    image: wazuh/wazuh-dashboard:${IMAGE_TAG}
    networks:
      traefik-internetwork:
        aliases:
          - wazuh.dashboard
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure  
      placement:
        constraints:
          - node.labels.codename == ${WAZUH_DASHBOARD_NODE_CODENAME}
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    environment:
      - INDEXER_USERNAME=${INDEXER_ADMIN_USERNAME}
      - INDEXER_PASSWORD=${INDEXER_ADMIN_PASSWORD}
      - WAZUH_API_URL=https://wazuh.manager:55000
      - DASHBOARD_USERNAME=${DASHBOARD_USERNAME}
      - DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
    configs:
      - source: wazuh.dashboard.pem
        target: /usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - source: wazuh.dashboard-key.pem
        target: /usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - source: root-ca.pem
        target: /usr/share/wazuh-dashboard/certs/root-ca.pem
      - source: wazuh-dashboard-opensearch-config
        target: /usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - source: wazuh-general-config
        target: /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
    volumes:
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
      - wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom

configs:
  wazuh-manager-config:
    external: true
  wazuh-indexer-config:
    external: true
  internal-users-config:
    external: true
  wazuh-dashboard-opensearch-config:
    external: true
  wazuh-general-config:
    external: true
  wazuh.manager.pem:
    external: true
  wazuh.manager-key.pem:
    external: true
  root-ca-manager.pem:
    external: true
  wazuh.indexer.pem:
    external: true
  wazuh.indexer-key.pem:
    external: true
  admin.pem:
    external: true
  admin-key.pem:
    external: true
  root-ca.pem:
    external: true
  wazuh.dashboard.pem:
    external: true
  wazuh.dashboard-key.pem:
    external: true

volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_wodles:
  filebeat_etc:
  filebeat_var:
  wazuh-indexer-data:
  wazuh-dashboard-config:
  wazuh-dashboard-custom:

networks:
  traefik-internetwork:
    external: true
