apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey-password-eso
  namespace: databases
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: valkey-password-eso
    creationPolicy: Owner
  data:
    - secretKey: valkey-auth-password
      remoteRef:
        key: docker-secrets
        property: valkey-auth-password
