apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudflare-cert-traefik
  namespace: traefik
spec:
  secretName: cloudflare-cert-traefik # This is the TLS secret used in Ingress
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  commonName: "vn.mcb-svc.work"
  dnsNames:
  - "vn.mcb-svc.work"
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiry
